### PR TITLE
Use requirements.txt, add pytype, add use of temporary directories in…

### PR DESCRIPTION
**Pull request by anarkiwi**
… tests, add example cert instructions.

### CODE REVIEW

**Comment by anarkiwi** [comment]
Thanks Bob. How about 2 PRs, one that has only changes to agenttest.py and another that adds requirements.txt etc?

Re .gitignore - it's true, this does accumulate stuff over time - I guess as different people have different environments and different IDEs etc. I can optimize it for today for sure, but I don't know a way to ensure it stays small over time?

**Comment by gizmoguy** [comment]
Regarding gitignore, you probably just want to use the Github default one for python:

https://github.com/github/gitignore/blob/master/Python.gitignore

**Comment by anarkiwi** [comment]
OK, I followed your recommendation and used the github one.

I guess could optimize it down but is that a long term maintainability issue as things come and go in this repo?

**Comment by gizmoguy** [comment]
I think you can safely remove the following sections from the .gitignore:

* PyInstaller
* Django stuff
* Flask stuff
* Scrapy stuff
* Sphinx documentation
* PyBuilder
* Jupyter Notebook
* IPython
* Celery stuff
* SageMath parsed files
* Spyder project settings
* Rope project settings
* mkdocs documentation
* mypy
* Pyre type checker
* Cython debug symbols

**Comment by anarkiwi** [comment]
OK, I made some changes to gitignore.

I can slice the PR some different ways if that's a blocker - e.g. agenttest.py only, other changes only?

**Comment by gizmoguy** [comment]
Yip slice it up into a few different PRs to make it easier to review, I think one for:

* adding requirements.txt
* adding .gitignore
* adding pytype
* updating docs
* using temp directories in the tests

**Comment by anarkiwi** [comment]
OK I will close this 1 PR and create 5 new PRs.

**Comment by anarkiwi** [comment]
6 apologies I counted incorrectly.

**Pull request closed without merging**
