### PR TITLE
add mininet dependency for tests

### PR DESCRIPTION
**Pull request by cglewis**

### CODE REVIEW

**Comment by gizmoguy** [comment]
Thanks @cglewis I guess you found this before we announced it :)

**Comment by lantz** [comment]
I don't understand this change.

The dependencies are installed by `dependencies.sh`, so why would we want to add an additional installation step in the makefile?

**Comment by cglewis** [comment]
@lantz if the system you're running the test on doesn't already have mininet installed it fails. this change ensures that mininet is installed before running the tests.

**Comment by lantz** [comment]
The test dependencies are installed in `.travis.yml` but I think this is an argument for creating a test dependency script.

**Comment by cglewis** [comment]
I don't have a strong preference either way, was just trying to make it a repeatable process for testing without travis.

**Comment by lantz** [comment]
Installing mininet with `pip3` isn't sufficient, because it doesn't install the `mn` helper tool which mininet needs in order to run.

**Comment by lantz** [comment]
@cglewis I created #3 to address this - if you have no objections, then we can merge it in.

**Comment by cglewis** [comment]
looks good to me, thanks for clarifying that and fixing :)

**Pull request merged**
